packer-base
Otus-DevOps-2022-11/sergey_shapovalov_infra pull request #5
Opened 2023-01-27 11:23 UTC by ssh500

# Выполнено HW-7

 - [+] Основное ДЗ
 - [+] Задание со *

Настроен immutable.json  с автозапуском через systemd init unit
Добавлена доп переменная в variables.json.example

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
cd packer; packer build --var-file=variables.json ubuntu16.json создается образ, далее из этого образа делается VM в Yandex Cloud. Авторизуемся по ssh, cd /home/ubuntu/reddit/ далее puma -d

Для запуска автоматического образа: 
cd packer; packer build --var-file=variables.json immutable.json 
Далее из этого образа делается VM в Yandex Cloud, после запуска VM всё будет работать.

## Как проверить работоспособность:
 - Например, перейти по ссылке http://EXT_IP:9292

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-01-28 14:26 UTC, mrgreyves requested changes
Здравствуйте!)
Переименуйте файл с переменными в variables.json.example
Так же добавьте "фейковый" ключ
Приключение минут на 10
ДЗ нужно поправить =)

2023-01-28 14:27 UTC, ssh500 commented
Добрый вечер, сейчас посмотрю.

2023-01-28 14:37 UTC, ssh500 commented
Готово.

2023-01-29 15:35 UTC, mrgreyves requested changes
Здравствуйте!)
Нужно поправить файл с переменными

2023-01-29 15:35 UTC, mrgreyves commented on packer/variables.json.example
> +  "service_account_key_file": "....json"
Нет запятой

2023-01-29 18:26 UTC, ssh500 commented on packer/variables.json.example
> +  "service_account_key_file": "....json"
Спасибо, поправил файл, теперь даже тесты проходят.)

2023-01-30 05:58 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все круто =)

2023-02-14 12:21 UTC, merged