Terraform 1
Otus-DevOps-2022-11/sergey_shapovalov_infra pull request #6
Opened 2023-02-05 19:07 UTC by ssh500

# Выполнено ДЗ № 08 Terraform-1

 - [ + ] Основное ДЗ
 - [ - ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - terraform apply -auto-approve

## Как проверить работоспособность:
 -  http://IP:9292

## PR checklist
 - [ + ] Выставил label с номером домашнего задания
 - [ + ] Выставил label с темой домашнего задания

2023-02-08 12:19 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарии к файлам, нужно поправить =)

2023-02-08 12:19 UTC, mrgreyves commented on terraform/variables.tf
> +variable "cloud_id" {
Нужно переименовать в variables.json.example

2023-02-08 12:19 UTC, mrgreyves commented on terraform/main.tf
> +terraform {
Определение провайдера перед коммитом стоит закомментировать =)

2023-02-09 14:09 UTC, ssh500 commented on terraform/variables.tf
> +variable "cloud_id" {
Done.

2023-02-09 14:09 UTC, ssh500 commented on terraform/main.tf
> +terraform {
Done.

2023-02-11 15:49 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув =)

2023-02-14 12:35 UTC, merged